Use urllib3.util.retry from requests.packages [RHELDST-5671]
Fixes
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

Requests module historically bundled its own urllib3,
which makes the whole Session-HTTPAdapter-Retry chain behave
unexpectedly. HTTPAdapter always calls Retry.from_int() regardless
of the max_retries parameter type. Retry.from_int() method either
creates a new instance of Retry or compares if the parameter already
is a Retry instance and returns it unchanged. The problem here is
that urllib3.util.retry.Retry is not the same as
requests.packages.urllib3.util.retry.Retry, so the non-bundled retry
object is wrapped into the bundled Retry object and is treated
as integer from then on, leading to the TypeError above.

Sufficiently new versions of requests module (>=2.16) stopped bundling
its own urllib3, but ship with a backwards-compatibility module which
still provides requests.packages.urllib3.util.retry.Retry which is
once again an alias of urllib3.util.retry

RHEL-6 and RHEL-7 python-requests packages ship their own version of
requests.packages.urllib3.* which aliases the real top-level urllib3
module, so this code adjustment should work even on legacy systems
without urllib3 bundled with requests.